# Generated by Django 5.0.6 on 2024-07-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaivarity",
            name="discription",
            field=models.TextField(default=""),
        ),
    ]
